routes/admin.php
<?php

/*
|--------------------------------------------------------------------------
| Admin Routes
|--------------------------------------------------------------------------
*/ 

// Route::get('/', 'AdminController@dashboard')->name('index');
Route::get('/notification', 'AdminController@notification')->name('notification');
Route::get('/dashboard', 'AdminController@dashboard')->name('dashboard');
// Route::get('/searchingajax', 'AdminController@searchingajax');
// Route::get ('/ajaxforofflineprovider' , 'AdminController@ajaxforofflineprovider');

Route::get('/airport', 'AdminController@airport')->name('airport');
Route::get('/delivery', 'AdminController@delivery')->name('delivery');
Route::get('/rental', 'AdminController@rental')->name('rental');
Route::get('/surge', 'AdminController@dashboard')->name('surge');
Route::get('cabAllocation', 'AdminController@cabAllocation')->name('cabAllocation');
Route::get('cabAllocation_update', 'AdminController@cabAllocation_update')->name('cabAllocation_update');
Route::get('cabAllocation_edit/{id}', 'AdminController@cabAllocation_edit')->name('cabAllocation_edit');

Route::get('allocation_list', 'AdminController@allocation_list')->name('allocation_list');
Route::get('/translation',  'AdminController@translation')->name('translation');
Route::get('/heatmap', 'AdminController@heatmap')->name('heatmap');
Route::get('/translation',  'AdminController@translation')->name('translation');

Route::group(['as' => 'dispatcher.', 'prefix' => 'dispatcher'], function () {
	Route::get('/', 'DispatcherController@index')->name('index');
	Route::post('/', 'DispatcherController@store')->name('store');
	Route::get('/trips', 'DispatcherController@trips')->name('trips');
	Route::get('/trips/{trip}/{provider}', 'DispatcherController@assign')->name('assign');
	Route::get('/users', 'DispatcherController@users')->name('users');
	Route::get('/providers', 'DispatcherController@providers')->name('providers');
});

Route::get('/zone/getCountry','Resource\ZoneResource@getCountry')->name('getcountry');
Route::get('/zone/getState','Resource\ZoneResource@getState')->name('getstate');
Route::get('/zone/getCity','Resource\ZoneResource@getCity')->name('getcity');
Route::get('/pushnotification/testUrl', 'PushNotificationResource@getZoneId');
Route::get('/pushnotification/getZoneProviders/{id}/{typeid}', 'Resource\PushNotificationResource@getZonesProviders')->name('pushzoneproviders');
Route::get('/pushnotification/getProvidersAndUsers/{typeid}', 'Resource\PushNotificationResource@getProvidersAndUsers')->name('getProvidersAndUsers');

Route::get('/pushnotification/getZones', 'Resource\PushNotificationResource@getZones')->name('allzones');

Route::resource('zone', 'Resource\ZoneResource');
Route::resource('pushnotification', 'Resource\PushNotificationResource');
Route::resource('country', 'Resource\CountryResource');
Route::resource('state', 'Resource\StateResource');
Route::resource('city', 'Resource\CityResource');
Route::resource('location', 'Resource\LocationResource');
Route::resource('user', 'Resource\UserResource');
Route::resource('dispatch-manager', 'Resource\DispatcherResource');
Route::resource('account-manager', 'Resource\AccountResource');
Route::resource('fleet', 'Resource\FleetResource');
Route::resource('provider', 'Resource\ProviderResource');
Route::resource('document', 'Resource\DocumentResource');
Route::resource('service', 'Resource\ServiceResource');
Route::resource('blog', 'Resource\BlogAdminResource');
Route::resource('allocation', 'Resource\ServiceResource@allocation');
Route::post('service_update/{id}', 'AdminController@service_update')->name('update');
Route::post('is_read','AdminController@is_read_post');
Route::get('faresettings', 'AdminController@fare_settings')->name('fare_settings');
Route::post('faresettings/store', 'AdminController@fare_settings_store')->name('fare.settings.store');
Route::get('settings/create', 'AdminController@fare_settings_create')->name('fare.settings.create');
Route::post('destory_fare', 'AdminController@destory_fare')->name('destory_fare');
Route::delete('delete_fare', 'AdminController@deleteFare')->name('fare.settings.destroy');
Route::delete('destory_pkg', 'AdminController@deletePKG')->name('fare.settings.deletePKG');
Route::get('edit_fare/{id}', 'AdminController@editFare')->name('fare.settings.edit');
Route::post('edit_fare_action', 'AdminController@editFareAction');
Route::post('addpeakAnight', 'AdminController@addpeakAnight')->name('peakNight');
Route::post('settings/addpeakAnight', 'AdminController@addpeakAnight');

Route::resource('bank', 'Resource\BankResource');
Route::resource('new_account', 'Resource\BankResource@new_account');
Route::get('approved_account', 'Resource\BankResource@approved_account');
Route::get('new_withdraw', 'Resource\BankResource@new_withdraw');
Route::get('approved_withdraw', 'Resource\BankResource@approved_withdraw');
Route::get('disapproved_withdraw', 'Resource\BankResource@disapproved_withdraw');

Route::resource('faqs', 'Resource\AdminFaqResource');    
Route::resource('how-it-work', 'Resource\AdminHowitWorkResource');    
Route::resource('page', 'Resource\PageAdminResource');
Route::resource('cms-manager', 'Resource\CmsResource');
Route::resource('support-manager', 'Resource\SupportResource');
Route::get('/support/open-ticket', 'Resource\SupportResource@openTicket')->name('openTicket');
Route::get('/support/close-ticket', 'Resource\SupportResource@closeTicket')->name('closeTicket');
Route::get('/support/open-ticket-details/{id}', 'Resource\SupportResource@openTicketDetails')->name('openTicketDetails');
Route::patch('/support/transfer/{id}', 'Resource\SupportResource@transfer')->name('transfer');
Route::resource('crm-manager', 'Resource\CrmResource');
Route::get('/lost-management', 'AdminController@lost_management')->name('lost-management');
Route::get('/lost-edit/{id}', 'AdminController@lost_edit')->name('lost-edit');
Route::PATCH('/lost-update/{id}', 'AdminController@lost_update')->name('lost-update');
Route::get('/crm/open-ticket/{type?}', 'Resource\CrmResource@openTicket')->name('openTicket');
Route::get('/crm/open-ticket-details/{id}', 'Resource\CrmResource@openTicketDetails')->name('openTicketDetails');
Route::patch('/crm/transfer/{id}', 'Resource\CrmResource@transfer')->name('transfer');
Route::get('/crm/close-ticket', 'Resource\CrmResource@closeTicket')->name('closeTicket');

Route::get('promocode/user', 'Resource\PromocodeResource@userPromoCode')->name('promocode.users');
Route::get('promocode/promocodes', 'Resource\PromocodeResource@getPromoCodes')->name('promocodes');
Route::get('promocode/promocodeusage', 'Resource\PromocodeResource@getPromocodeUser')->name('promocodeusage');

Route::get('reward', 'Resource\PromocodeResource@rewardRuleIndex')->name('reward.index');
Route::get('reward/create', 'Resource\PromocodeResource@rewardRuleCreate')->name('reward.create');
Route::post('reward', 'Resource\PromocodeResource@rewardRuleUpdate')->name('reward.updated');
Route::get('referral', 'Resource\PromocodeResource@referralRuleIndex')->name('referral.index');
Route::get('referral/create', 'Resource\PromocodeResource@referralRuleCreate')->name('referral.create');
Route::post('referral', 'Resource\PromocodeResource@referralRuleUpdate')->name('referral.updated');


Route::resource('promocode', 'Resource\PromocodeResource');
Route::resource('testimonial', 'Resource\TestimonialResource');

Route::group(['as' => 'provider.'], function () {
    Route::get('review/provider', 'AdminController@provider_review')->name('review');
    Route::get('provider/{id}/approve', 'Resource\ProviderResource@approve')->name('approve');
    Route::get('provider/{id}/disapprove', 'Resource\ProviderResource@disapprove')->name('disapprove');
    Route::get('provider/{id}/request', 'Resource\ProviderResource@request')->name('request');
    Route::get('provider/{id}/statement', 'Resource\ProviderResource@statement')->name('statement');
    Route::resource('provider/{provider}/document', 'Resource\ProviderDocumentResource');
    Route::delete('provider/{provider}/service/{document}', 'Resource\ProviderDocumentResource@service_destroy')->name('document.service');
    Route::get('provider/{provider}/document/{document}/upload', 'Resource\ProviderDocumentResource@get_provider_document_upload');
	Route::post('provider/{provider}/document/{document}/upload', 'Resource\ProviderDocumentResource@provider_document_upload');
	Route::get('provider/{provider}/document/{document}/update', 'Resource\ProviderDocumentResource@edit_provider_document_upload');
	Route::post('provider/{provider}/document/{document}/update', 'Resource\ProviderDocumentResource@update_provider_document_upload');
	
});

Route::get('review/user', 'AdminController@user_review')->name('user.review');
Route::get('user/{id}/request', 'Resource\UserResource@request')->name('user.request');

Route::get('map', 'AdminController@map_index')->name('map.index');
Route::get('map/ajax', 'AdminController@map_ajax')->name('map.ajax');

Route::get('settings', 'AdminController@settings')->name('settings');
Route::post('settings/store', 'AdminController@settings_store')->name('settings.store');
Route::get('settings/payment', 'AdminController@settings_payment')->name('settings.payment');
Route::post('settings/payment', 'AdminController@settings_payment_store')->name('settings.payment.store');

Route::get('profile', 'AdminController@profile')->name('profile');
Route::post('profile', 'AdminController@profile_update')->name('profile.update');
Route::get('/contact', 'AdminController@contact')->name('contact');
Route::delete('/destroy/{id}', 'AdminController@destroy')->name('destroy');

Route::get('password', 'AdminController@password')->name('password');
Route::post('changeprovidorpassword', 'AdminController@changeprovidorpassword')->name('changeprovidorpassword');
Route::post('changeuserpassword', 'AdminController@changeuserpassword')->name('changeuserpassword');

routes/web.php
<?php

/*

|--------------------------------------------------------------------------

| User Authentication Routes

|--------------------------------------------------------------------------

*/

if (version_compare(PHP_VERSION, '7.2.0', '>=')) {
    // Ignores notices and reports all other kinds... and warnings
    error_reporting(E_ALL ^ E_NOTICE ^ E_WARNING);
    // error_reporting(E_ALL ^ E_WARNING); // Maybe this is enough
}

use App\ServiceType;

use App\Testimonial;

use App\Page;

// Get Route For Show Payment Form
Route::get('/notification-test',function(){
    
	$push_message = 'Test Notification';
	$img="";
	$msg_type = 'test';
	$to = 'dxsPjXgTiCQ:APA91bEjnKhg_BjZKrr05Ome2_9KUO6mElaEJA5IxfSxsSuilg3v98J14LLaF155NJdTzFum6sV3MRNakPV3N277RXuDLx-lHYcW-eck4s6cPYpSofo7H1kaC51vd-7FYWKqGl9v4NPI';
	$url = 'https://fcm.googleapis.com/fcm/send';
    $notify = shell_exec('curl -X POST --header "Authorization: key=AAAAlu8IUPo:APA91bHlXZh-KMu4ydG8JkEsNbG5mcx2rhXAb_m0alzQ7_YzaYQyiqOuibY07_VtZ0I_cWCaJIjgsGubgA4qLJFRxpchy2GyOglewGKM0pJ_mBxt3cQ6s2uxEhVf6Mjwigg326oIcIID" --header "Content-Type: application/json" https://fcm.googleapis.com/fcm/send -d "{\"to\":\"'.$to.'\",\"priority\":\"high\",\"data\":{\"msg_type\":\"'.$msg_type.'\",\"msg\":\"'.$push_message.'\"},\"message_type\":\"chat\",\"notification\":{\"body\": \"'.stripslashes($push_message).'\",\"title\":\"'.$msg_type.'\",\"image\":\"'.$img.'\"}}"');         

    return $notify;
});

Route::get('paywithrazorpay', 'RazorpayController@payWithRazorpay')->name('paywithrazorpay');

Route::get('/whoami101', function () {return view('my-page');});

Route::get('payThankYou', 'RazorpayController@payThankYou')->name('payThankYou');

// Post Route For Makw Payment Request

Route::post('razorpay_payment', 'RazorpayController@payment')->name('payment');

Auth::routes();



Route::get('auth/facebook', 'Auth\SocialLoginController@redirectToFaceBook');

Route::get('auth/facebook/callback', 'Auth\SocialLoginController@handleFacebookCallback');

Route::get('auth/google', 'Auth\SocialLoginController@redirectToGoogle');

Route::get('auth/google/callback', 'Auth\SocialLoginController@handleGoogleCallback');

Route::post('account/kit', 'Auth\SocialLoginController@account_kit')->name('account.kit');

//Route::get('/searchingajax', 'AdminController@searchingajax');

/*

|--------------------------------------------------------------------------

| Provider Authentication Routes

|--------------------------------------------------------------------------

*/



Route::group(['prefix' => 'provider'], function () {



    Route::get('auth/facebook', 'Auth\SocialLoginController@providerToFaceBook');

    Route::get('auth/google', 'Auth\SocialLoginController@providerToGoogle');



    // Route::get('/login', 'ProviderAuth\LoginController@showLoginForm')->middleware('accesspage');

    Route::get('/login', 'ProviderAuth\LoginController@showLoginForm');

    // Route::get('/login', 'ProviderAuth\LoginController@showLoginForm');

    // Route::get('/login', 'ProviderAuth\LoginController@login');

    Route::post('/login', 'ProviderAuth\LoginController@login');

    Route::post('/logout', 'ProviderAuth\LoginController@logout');



    // Route::get('/register', 'ProviderAuth\RegisterController@showRegistrationForm')->middleware('accesspage');



    Route::get('/register', 'ProviderAuth\RegisterController@showRegistrationForm');

    Route::post('/register', 'ProviderAuth\RegisterController@register');



    Route::post('/password/email', 'ProviderAuth\ForgotPasswordController@sendResetLinkEmail');

    Route::post('/password/reset', 'ProviderAuth\ResetPasswordController@reset');

    Route::get('/password/reset', 'ProviderAuth\ForgotPasswordController@showLinkRequestForm');

    Route::get('/password/reset/{token}', 'ProviderAuth\ResetPasswordController@showResetForm');

    Route::post('/password/update', 'CommonController@provider_password_update');

});



/*

|--------------------------------------------------------------------------

| Admin Authentication Routes

|--------------------------------------------------------------------------

*/



Route::group(['prefix' => 'admin'], function () {

    Route::get('/',function(){

        return redirect()->route('admin.login');

    });
    Route::get('/search_shedule_provider', 'CommonController@search_shedule_provider');
    Route::get('/searchingajax', 'CommonController@searchingajax');

    Route::get ('/ajaxforofflineprovider' , 'CommonController@ajaxforofflineprovider');

    Route::get ('/offnotificationtoprovider' , 'SendPushNotification@offnotificationtoprovider');

    

    Route::get ('/provider-document-expiry-notification' , 'CommonController@providerDocumentExpiryNotification');

    // Route::get('/login', 'AdminAuth\LoginController@showLoginForm')->middleware('accesspage');

    Route::get('/login', 'AdminAuth\LoginController@showLoginForm')->name('admin.login');

    Route::post('/login', 'AdminAuth\LoginController@login');

    Route::post('/logout', 'AdminAuth\LoginController@logout');



    Route::post('/password/email', 'AdminAuth\ForgotPasswordController@sendResetLinkEmail');

    Route::post('/password/reset', 'AdminAuth\ResetPasswordController@reset');

    Route::get('/password/reset', 'AdminAuth\ForgotPasswordController@showLinkRequestForm');

    Route::get('/password/reset/{token}', 'AdminAuth\ResetPasswordController@showResetForm');

});



/*

|--------------------------------------------------------------------------

| Dispatcher Authentication Routes

|--------------------------------------------------------------------------

*/



Route::group(['prefix' => 'dispatcher'], function () { 

  Route::get('/',function(){

   return redirect()->route('dispatcher.login');

  });  

  Route::get('/login', 'DispatcherAuth\LoginController@showLoginForm')->name('dispatcher.login');

  Route::post('/login', 'DispatcherAuth\LoginController@login');

  Route::post('/logout', 'DispatcherAuth\LoginController@logout');



  Route::post('/password/email', 'DispatcherAuth\ForgotPasswordController@sendResetLinkEmail');

  Route::post('/password/reset', 'DispatcherAuth\ResetPasswordController@reset');

  Route::get('/password/reset', 'DispatcherAuth\ForgotPasswordController@showLinkRequestForm');

  Route::get('/password/reset/{token}', 'DispatcherAuth\ResetPasswordController@showResetForm');

});



/*

|--------------------------------------------------------------------------

| Fleet Authentication Routes

|--------------------------------------------------------------------------

*/





Route::group(['prefix' => 'fleet'], function () {

  Route::get('/',function(){

   return redirect()->route('fleet.login');

  });

  Route::get('/login', 'FleetAuth\LoginController@showLoginForm')->name('fleet.login');

  Route::post('/login', 'FleetAuth\LoginController@login');

  Route::post('/logout', 'FleetAuth\LoginController@logout');



  Route::post('/password/email', 'FleetAuth\ForgotPasswordController@sendResetLinkEmail');

  Route::post('/password/reset', 'FleetAuth\ResetPasswordController@reset');

  Route::get('/password/reset', 'FleetAuth\ForgotPasswordController@showLinkRequestForm');

  Route::get('/password/reset/{token}', 'FleetAuth\ResetPasswordController@showResetForm');

});



/*

|--------------------------------------------------------------------------

| Web Routes

|--------------------------------------------------------------------------

*/

Route::get('lang/{locale}', 'LocalizationController@index');

Route::get('/', function () {

    $services   = ServiceType::all();  

    $index   = Page::where('en_meta_keys','index')->get();  

    $testimonials = Testimonial::all();

   
    
    return view('index', compact(['services','testimonials','index']) );

});



Route::post('/get_fare', 'AjaxHandlerController@estimated_fare')->name('getfare');

Route::post('/saveLocationTemp', 'AjaxHandlerController@saveLocationTemp');



Route::post('/locale', 'CommonController@locale' );

Route::get('/fare_estimate', 'CommonController@fare_estimate');

Route::get('/helppage', 'CommonController@helpPage');





/*

|--------------------------------------------------------------------------

| User Routes

|--------------------------------------------------------------------------

*/



/*

|--------------------------------------------------------------------------

| My Files

|--------------------------------------------------------------------------

*/

//User sign in

Route::get('/login', 'SignInControlller@passengerSignin')->middleware('accesspage');

// Route::get('/PassengerSignin', 'SignInControlller@passengerSignin')->middleware('accesspage');

Route::get('/PassengerSignin', 'SignInControlller@passengerSignin');

Route::get('/faq', 'HomeController@faqs');

Route::get('/terms', 'HomeController@terms');

Route::get('/help', 'HomeController@helps');



Route::get('/dashboard', 'HomeController@index');

Route::get('/mytrips', 'HomeController@mytrips');

Route::get('/mytrips/detail', 'HomeController@mytrips_details');



// user profiles

Route::get('/profile', 'HomeController@profile');

Route::get('/edit/profile', 'HomeController@edit_profile');

Route::post('/profile', 'HomeController@update_profile');



// update password

Route::get('/change/password', 'HomeController@change_password');

Route::post('/change/password', 'HomeController@update_password');

Route::post('/password/update', 'CommonController@password_update'); 

// ride 

Route::get('/confirm/ride', 'RideController@confirm_ride');

Route::post('/create/ride', 'RideController@create_ride');

Route::post('/cancel/ride', 'RideController@cancel_ride');

Route::get('/onride', 'RideController@onride');

Route::post('/payment', 'PaymentController@payment');

Route::get('/payment/paypal/status', ['middleware' => 'auth', 'uses' => 'PaymentController@getPaymentStatus'])->name('paypalbookingstatus');

resources/views/admin/zone/edit.blade.php
@extends('admin.layout.base')

@section('title', 'Update  Zone ')

@section('content')


<div class="content-area py-1">
    <div class="container-fluid">
    	<div class="box box-block bg-white">
    	    <!-- <a href="{{ route('admin.zone.index') }}" class="btn btn-default pull-right"><i class="fa fa-angle-left"></i> Back</a> -->

			<h5 style="margin-bottom: 2em;"><span class="s-icon"><i class="ti-zoom-in"></i></span>&nbsp;Update  Zone</h5><hr>

            <!--form class="form-horizontal" action="{{route('admin.zone.update', $zone->id )}}" method="POST" enctype="multipart/form-data" role="form">
            	{{csrf_field()}}
            	<input type="hidden" name="_method" value="PATCH">
				<div class="form-group row">
					<label for="name" class="col-xs-2 col-form-label">Zone Name</label>
					<div class="col-xs-10">
						<input class="form-control" type="text" value="{{ $zone->name }}" name="name" required id="name" placeholder="Zone Name">
					</div>
				</div>

                <div class="form-group row">
                    <label for="name" class="col-xs-2 col-form-label">Zone Type</label>
                    <div class="col-xs-10">
                        <input class="form-control" type="text" value="{{ $zone->type }}" name="type" required id="type" placeholder="Zone Type">
                    </div>
                </div>

             <div class="form-group row">
					<label for="name" class="col-xs-2 col-form-label">Country </label>
					<div class="col-xs-10">
						<input class="form-control" type="text" value="{{ $zone->county }}" name="county" required id="country" placeholder="Country">
					</div>
				</div>

                <div class="form-group row">
                    <label for="name" class="col-xs-2 col-form-label">Province</label>
                    <div class="col-xs-10">
                        <input class="form-control" type="text" value="{{ $zone->province }}" name="province" required id="province" placeholder="Province">
                    </div>
                </div>


                <div class="form-group row">
					<label for="name" class="col-xs-2 col-form-label">Province Code </label>
					<div class="col-xs-10">
						<input class="form-control" type="text" value="{{ $zone->province_code }}" name="province_code" required id="province_code" placeholder="Province code">
					</div>
				</div>

                <div class="form-group row">
                    <label for="name" class="col-xs-2 col-form-label">Postcode area</label>
                    <div class="col-xs-10">
                        <input class="form-control" type="text" value="{{ $zone->postcode_area }}" name="postcode_area" required id="province" placeholder="Postcode area">
                    </div>
                </div>


                <div class="form-group row">
                    <label for="name" class="col-xs-2 col-form-label">Area Code</label>
                    <div class="col-xs-10">
                        <input class="form-control" type="text" value="{{ $zone->area_code }}" name="area_code" required id="area_code" placeholder="Area Code">
                    </div>
                </div>

	 <div class="form-group row">
                    <label for="Latitude" class="col-xs-2 col-form-label">Latitude</label>
                    <div class="col-xs-10">
                        <input class="form-control" type="text" value="{{ $zone->latitude }}" name="latitude" required id="latitude" placeholder="Latitude">
                    </div>
                </div>
				 <div class="form-group row">
                    <label for="Longitude" class="col-xs-2 col-form-label">Longitude</label>
                    <div class="col-xs-10">
                        <input class="form-control" type="text" value="{{ $zone->longitude }}" name="longitude" required id="longitude" placeholder="Longitude">
                    </div>
                </div>
				<div class="form-group row">
					<label for="zipcode" class="col-xs-2 col-form-label"></label>
					<div class="col-xs-10">
						<button type="submit" class="btn btn-primary">Update Zone</button>
						<a href="{{route('admin.zone.index')}}" class="btn btn-default">Cancel</a>
						
					</div>
				</div>
			</form-->
		</div>
    </div>
</div>

@endsection

resources/views/admin/zone/index.blade.php
@extends('admin.layout.base')

@section('title', 'Locations ')

@section('content')

    <div class="content-area py-1">
        <div class="container-fluid">
            
            <div class="box box-block bg-white">
                <h5 class="mb-1"><span class="s-icon"><i class="ti-zoom-in"></i></span> &nbsp;Zones </h5>
                <hr/>
                <a href="{{ route('admin.zone.create') }}" style="margin-left: 1em;" class="btn shadow-box btn-success btn-rounded w-min-sm m-b-0-25 waves-effect waves-light pull-right"><i class="fa fa-plus"></i> Add New Location</a>
                <table class="table table-striped table-bordered dataTable" id="table-2" style="width:100%;">
                    <thead>
                        <tr>
                            <th>ID</th>
                            <th>Zone Name</th>
                            <th>Country</th>
                            <th>State</th>
                            <th>City</th>
                            <th>Currency</th>
                            <th>Status</th>
                            <th>Created</th>
                            <th style="width:50px;">Action</th>
                        </tr>
                    </thead>
                    <tbody>
                    @foreach($zones as $index => $zone)
                        <tr>
                            <td>{{$index + 1}}</td>
                            <td>{{$zone->zone_name}}</td>
                            <td>{{$zone->country}}</td>
                            <td>{{$zone->state}}</td>
                            <td>{{$zone->city}}</td>
                            <td>{{$zone->currency}}</td>
                            <td>{{$zone->status}}</td>
                            <td>{{ date('Y-m-d: H:i:A', strtotime( $zone->created_at ) )}}</td>
                            <td style="width: 100px;">
                                <form action="{{ route('admin.zone.destroy', $zone->id) }}" method="POST">
                                    {{ csrf_field() }}
                                    <input type="hidden" name="_method" value="DELETE">
                                    <a href="{{ route('admin.zone.edit', $zone->id) }}" class="btn shadow-box btn-black"><i class="fa fa-eye"></i></a>
                                    <button class="btn shadow-box btn-danger" onclick="return confirm('Are you sure?')"><i class="fa fa-trash"></i></button>
                                </form>
                            </td>
                        </tr>
                    @endforeach
                    </tbody>
                    <tfoot>
                        <tr>
                            <th>ID</th>
                            <th>Location Name</th>
                            <th>Country</th>
                            <th>State</th>
                            <th>City</th>
                            <th>Currency</th>
                            <th>Status</th>
                            <th>Created at</th>
                            <th>Action</th>
                        </tr>
                    </tfoot>
                </table>
            </div>
            
        </div>
    </div>
@endsection